### ISSUE TITLE
Progress is reset after each restart

### ISSUE THREAD

**Issue by ivenassenkamp** [D151l/rPlace#38]
The progress (displayed in the sidebar) is reset after each restart of the server
![image](https://github.com/D151l/rPlace/assets/26743278/99c8ff9d-8e59-4231-afe8-a4794efc4e40)

**Comment by D151l** [comment]
Moin, 
I have fixed this bug in my newest version. You can just update the plugin, but it's best to make a backup first....
It should not lead to any problems, at least it was like that in my tests.

https://github.com/D151l/rPlace/releases/tag/update-1.1
https://hangar.papermc.io/D151l/rPlace/versions/1.1
